### ISSUE TITLE
Switch Panel?

### ISSUE THREAD

**Issue by gcacciola** [dledeaux/jeep#1]
Hello Foco, how are you?

First of all, contratulations on your amazing job designing that Led Switch panel for the TJ.

I have my own 3d printer and knowledge to dremel, sand and paint the part as you mentioned at another thread.

I would love to have it printed, I saw that you made two other files available, are you willing to make this one available too? Even if you charge for it?

Thanks!

Best regards.

Giacomo

**Comment by dledeaux** [comment]
File has been upoaded
